# version 0.1

FROM CWDS/ruby:251

RUN apt-get install -y \
    chrpath \
    libssl-dev \
    libxft-dev \
    libfreetype6 \
    libfreetype6-dev \
    libfontconfig1 \
    libfontconfig1-dev \
    iceweasel \
    xvfb \
    bzip2 \
    qt5-default \
    libqt5webkit5-dev \
    gstreamer1.0-plugins-base \
    gstreamer1.0-tools \
    gstreamer1.0-x. \
    gconf2

RUN apt-get update -y
RUN apt-get upgrade -y

# install chrome binary
RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list

RUN apt-get update && apt-get install --no-install-recommends -y google-chrome-stable

RUN export CHROME_BIN=/usr/bin/google-chrome
